use_frameworks!

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, '9.0'

target 'CSModuleManager_Example' do
  pod 'CSModuleManager', :path => '../'

  target 'CSModuleManager_Tests' do
    inherit! :search_paths

    
  end
end
